CREATE DATABASE BIBLOS_DATABASE
USE BIBLOS_DATABASE
GO

/*TABLAS*/
CREATE TABLE CATEGORIA
(
	ID INT PRIMARY KEY IDENTITY,
	NOMBRE VARCHAR(50)
)

CREATE TABLE AUTOR
(
	ID INT PRIMARY KEY IDENTITY,
	NOMBRE VARCHAR(50)
)
GO


CREATE TABLE USUARIO
(
	ID INT PRIMARY KEY IDENTITY,
	NOMBRE VARCHAR (50) NOT NULL,
	CORREO VARCHAR (50) UNIQUE NOT NULL,
	CONTRASENA VARCHAR (15) NOT NULL,
	ROL VARCHAR (10) NOT NULL 
)
GO

CREATE TABLE LIBRO
(
	ID INT PRIMARY KEY IDENTITY,
	ISBN VARCHAR (12) UNIQUE NOT NULL,
	TITULO VARCHAR (100) NOT NULL,
	FECHA_PUBLICACION DATE,
	EDITORIAL VARCHAR (100) NOT NULL,
	CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID) NOT NULL,
	AUTOR INT FOREIGN KEY REFERENCES AUTOR(ID) NOT NULL,
	CANTIDAD INT DEFAULT(0)
)
GO

CREATE TABLE VENTA
(
	ID INT PRIMARY KEY IDENTITY,
	CLIENTE INT FOREIGN KEY REFERENCES USUARIO(ID) NOT NULL,
	LIBRO INT FOREIGN KEY REFERENCES LIBRO(ID) NOT NULL,
	CANTIDAD INT DEFAULT(1),
	FECHA DATE NOT NULL
)
GO

/*INSERTANDO VALORES EN LAS TABLAS*/

/*TABLA CATEGORIA*/

INSERT INTO CATEGORIA VALUES ('MISTERIO')
INSERT INTO CATEGORIA VALUES ('DRAMA')
INSERT INTO CATEGORIA VALUES ('ROMANCE')
INSERT INTO CATEGORIA VALUES ('CIENCIAS NATURALES')
INSERT INTO CATEGORIA VALUES ('MATEMÁTICAS')
INSERT INTO CATEGORIA VALUES ('CIENCIAS SOCIALES')
INSERT INTO CATEGORIA VALUES ('CIENCIA FICCIÓN')
INSERT INTO CATEGORIA VALUES ('CÓMICS')
INSERT INTO CATEGORIA VALUES ('AVENTURA')
INSERT INTO CATEGORIA VALUES ('TERROR')

/*TABLA AUTOR*/
INSERT INTO AUTOR VALUES ('JUAN SÁNCHEZ')
INSERT INTO AUTOR VALUES ('PEDRO MIR')
INSERT INTO AUTOR VALUES ('GABRIEL GARCÍA MÁRQUEZ')
INSERT INTO AUTOR VALUES ('PABLO NIEVES')
INSERT INTO AUTOR VALUES ('CARLOS SANTANA')
INSERT INTO AUTOR VALUES ('VIRGINIA PÉREZ')
INSERT INTO AUTOR VALUES ('SANTO RODRIGUEZ')
INSERT INTO AUTOR VALUES ('MARÍA PANIAGUA')
INSERT INTO AUTOR VALUES ('ROSA PAZ')
INSERT INTO AUTOR VALUES ('RUTH DE LA ROSA')

/*TABLA USUARIO*/
INSERT INTO USUARIO VALUES ('ÁMBAR LÓPEZ', 'AMBARLOPEZ@GMAIL.COM', 'AMBAR05', 'ADMIN')
INSERT INTO USUARIO VALUES ('ROSA AMADOR', 'ROSAAMADOR@GMAIL.COM', 'ROSA09', 'CLIENT')
INSERT INTO USUARIO VALUES ('LUIS SOTO', 'LUISSOTO@GMAIL.COM', 'LUIS08', 'CLIENT')
INSERT INTO USUARIO VALUES ('VÍCTOR PÉREZ', 'VICTORPEREZ@GMAIL.COM', 'VICTOR09', 'CLIENT')
INSERT INTO USUARIO VALUES ('CRISTIAN VARGAS', 'CRISTIANVARGAS@GMAIL.COM', 'CRISTIAN04', 'CLIENT')
INSERT INTO USUARIO VALUES ('KARINA SÁNCHEZ', 'KARINASANCHEZ@GMAIL.COM', 'KARINA03', 'CLIENT')
INSERT INTO USUARIO VALUES ('PERLA PEÑA', 'PERLAPENA@GMAIL.COM', 'PERLA45', 'CLIENT')
INSERT INTO USUARIO VALUES ('YESSICA PAZ', 'YESSICAPAZ@GMAIL.COM', 'YESSICA90', 'CLIENT')
INSERT INTO USUARIO VALUES ('RICHEL POZO', 'RICHELPOSO@GMAIL.COM', 'RICHEL06', 'CLIENT')
INSERT INTO USUARIO VALUES ('ESTHER GUZMÁN', 'ESTHERGUZMAN@GMAIL.COM', 'ESTHER67', 'CLIENT')

/*TABLA LIBRO*/
INSERT INTO LIBRO VALUES ('0-2645-26413', 'ABOUT FACE 2.0', '2007-06-03', 'EDITORIAL DEL CARIBE',1, 1, 20)
INSERT INTO LIBRO VALUES ('0-4645-26313', 'EL NIÑO QUE APRENDIÓ A SOÑAR', '11-08-2004', 'EDITORIAL RISITA', 4,2, 60)
INSERT INTO LIBRO VALUES ('0-2545-26413', 'AZUL', '1990-11-13', 'EDITORIAL AZUL', 4, 3,200)
INSERT INTO LIBRO VALUES ('0-7645-26213', 'MARIA', '2007-06-09', 'EDITORIAL ALEGRIA', 3, 3,10)
INSERT INTO LIBRO VALUES ('0-9645-26413', 'LUCECITA', '2007-06-20', 'EDITORIAL SUR', 3, 6 , 30)
INSERT INTO LIBRO VALUES ('0-9625-26313', 'UNA ISLA AZUL', '1790-06-28', 'EDITORIAL NORTE', 6, 8, 200)
INSERT INTO LIBRO VALUES ('0-6605-26410', 'LIBRO NACHO', '2000-06-08', 'EDITORIAL PEÑA', 9, 7, 300)
INSERT INTO LIBRO VALUES ('0-1645-26413', 'AZUL 2.0', '2005-08-21', 'EDITORIAL AZUL', 4, 3, 100)
INSERT INTO LIBRO VALUES ('0-7605-26413', 'FANTASIA', '2011-08-14', 'EDITORIAL DEL SOL', 1, 8, 20)
INSERT INTO LIBRO VALUES ('0-8645-26413', 'THE BLACK MOON', '2004-03-13', 'EDITORIAL BROWN', 5,7 , 80)

/*TABLA DE VENTAS*/
INSERT INTO VENTA VALUES (2, 1, 2, '2021-12-02')
INSERT INTO VENTA VALUES (3, 2, 3, '2021-12-03')
INSERT INTO VENTA VALUES (5, 3, 6, '2021-12-05')
INSERT INTO VENTA VALUES (4, 4, 10, '2021-12-04')
INSERT INTO VENTA VALUES (6, 5, 5, '2021-12-06')
INSERT INTO VENTA VALUES (7, 6, 7, '2021-12-10')
INSERT INTO VENTA VALUES (8, 7, 9, '2021-12-11')
INSERT INTO VENTA VALUES (9, 8, 5, '2021-12-09')
INSERT INTO VENTA VALUES (10, 9, 1, '2021-12-03')
INSERT INTO VENTA VALUES (3, 10, 8, '2021-12-01')
